language: swift
os: osx
osx_image: xcode10
xcode_project: QRCode.xcodeproj

matrix:
  include:
    - name: "macOS"
      xcode_scheme: QRCode_macOS
    - name: "iOS"
      #xcode_scheme: QRCode_iOS
      script:
        - set -o pipefail && xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.0,name=iPhone SE' -project QRCode.xcodeproj -scheme QRCode_iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty
    - name: "macOS Example App"
      xcode_scheme: Example_macOS
    - name: "iOS Example App"
      #xcode_scheme: Example_iOS
      script:
        - set -o pipefail && xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.0,name=iPhone SE' -project QRCode.xcodeproj -scheme Example_iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty
